### ISSUE TITLE
Remove unsecure swf file in player subfolder

### ISSUE THREAD

**Issue by Defcon0** [contao-components/mediabox#1]
Hello,

we just installed a system at a customer's server. But doing a `composer install` doesn't work because the firewall complains about the swf files in this module (same in https://github.com/contao-components/mediaelement). I skip creating an issue for this repo also until we found a solution for this issue.

The swf files seem to be in this module for fallback reasons. Is there a chance to remove these files asap? I could also provide a pull request but it seems to be very deeply integrated :-(

Thanks in advance for your opinion on this.

Bye!

**Comment by leofeyer** [comment]
> Is there a chance to remove these files asap?

No, because as you have said yourself, the .swf file is there as a fallback for older browsers. Removing the file would break the functionality in those browsers.

**Comment by Defcon0** [comment]
The fallback should go for the video element, right? The video element is supported from IE10 and upwards (https://caniuse.com/#feat=video). Contao has a minimum browser requirement of IE 11 (see https://github.com/contao/managed-edition/blob/4.8/README.md). So that means there shouldn't be a problem or am I missing something?

**Comment by ausi** [comment]
> the firewall complains about the swf files in this module

How does the firewall complain? Are there more details about a security issue in the SWF file? If the SWF file is unsecure we should probably fix it instead of deleting it.

**Comment by Defcon0** [comment]
I'll ask the customer for the logs but this may take a while, sry.

**Comment by leofeyer** [comment]
@Defcon0 Did you get the log files meanwhile?

**Comment by Defcon0** [comment]
Sorry, unfortunately not by now. I just contacted the customer again.

**Comment by Defcon0** [comment]
fyi: The customer opened a service desk ticket for this 1 week ago. I'll write again if something happens here.
